### ISSUE TITLE
Error when trying to create a Gnosis SAFE on Sepolia.

### ISSUE THREAD

**Issue by MicahZoltu** [DarkFlorist/TheInterceptor#815]
Brave, Interceptor 0.0.76, MetaMask, Signing mode.

https://app.safe.global/new-safe/create?chain=sep

When prompted whether to use a Relayer or Connected Wallet, choose Connected Wallet.

```
Error: could not decode result data (value="0x", info={ "method": "at", "signature": "at(address)" }, code=BAD_DATA, version=6.4.0)
```
```
at makeError (chrome-extension://hajhilgnjpioghneebhiccafdeoiadki/vendor/ethers/ethers.js:175:21)
at assert$1 (chrome-extension://hajhilgnjpioghneebhiccafdeoiadki/vendor/ethers/ethers.js:191:15)
at Interface.decodeFunctionResult (chrome-extension://hajhilgnjpioghneebhiccafdeoiadki/vendor/ethers/ethers.js:11644:9)
at getSimulatedCode (chrome-extension://hajhilgnjpioghneebhiccafdeoiadki/js/simulation/services/SimulationModeEthereumClientService.js:479:32)at async getCodeOrError (chrome-extension://hajhilgnjpioghneebhiccafdeoiadki/js/simulation/protectors/commonTokenOops.js:14:18)
at async eoaCalldata (chrome-extension://hajhilgnjpioghneebhiccafdeoiadki/js/simulation/protectors/eoaCalldata.js:7:18)
at async chrome-extension://hajhilgnjpioghneebhiccafdeoiadki/js/simulation/simulator.js:123:70
at async Promise.all (index 4)
at async runProtectorsForTransaction (chrome-extension://hajhilgnjpioghneebhiccafdeoiadki/js/simulation/simulator.js:124:21)
at async chrome-extension://hajhilgnjpioghneebhiccafdeoiadki/js/background/background.js:125:83
```

**Comment by MicahZoltu** [comment]
Same error in simulation mode.

**Comment by KillariDev** [comment]
this is because we haven't deployed `at()` contract on sepolia
